services:
  backend:
    build: ./spring-back-pr7
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_name
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db
    networks:
      - backend
      - frontend
  db:
    image: 'postgres:16'
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "db_name"
    networks:
      - backend
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  frontend:
    build: ./web-app-pr7
    depends_on:
      backend:
        condition: service_started
    environment:
      API_URL: http://backend
      BACKEND_PORT: "8080"
    networks:
      - frontend
    ports:
     - "80:80"

volumes:
  db-data: null

networks:
  frontend: {}
  backend: {}
